# chapter 04. word2vec speed improvement

In [ ]:
CBOW model is 2 layered model. it is simple, but takes longer time to process.  
in this chapter we aim to add 2 improvements.  
1. adding new layer called "Embedding"
2. by "Negative Sampling", we use new loss function.

## 4.1 word2vec improvement
input is one-hot vector. suppose there are 1M vocabulary. then single vector has 1M binary digits.  
=> solved by "Embedding"  
hidden layer * output layer is too much caculation  
=> solved by "Negative Sampling"

### 4.1.1 Embedding layer
one hot vector matrix multiplication is just extracting a row of matrix.  

### 4.1.2 Embedding layer implementation

In [1]:
import numpy as np
W = np.arange(21).reshape(7,3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [2]:
W[2]

array([6, 7, 8])

In [3]:
W[5]

array([15, 16, 17])

In [5]:
idx = np.array([1, 0, 3, 0 ])
W[idx]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [6]:
# common/layers.py
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None
        
    def forward(self, idx):
        W, =self.params
        